---
title: "Inferência Estatística I"
subtitle: "Lista 2"
author: 
  - name: Paulo Cerqueira Jr
    affiliations:
      - name: Faculdade de Estatística - FAEST
        address: 500 Lafayette Road Saint Paul, MN 55155
      - name: Universidade Federal do Pará - UFPA
        department: Instituto de Ciências Exatas e Naturais - ICEN
    email: cerqueirajr@ufpa.br
    orcid: "https://orcid.org/0000-0002-6310-5040"
    url: "https://github.com/paulocerqueirajr"
format: html
editor: visual
lang: pt
---

::: {#exr-exr1}
Seja $X_1, \ldots, X_n$ uma amostra aleatória da v.a. $X \sim \text{Poisson}(\theta)$. Considere os seguintes estimadores para $\theta$:
:::

$$
\hat{\theta}_1 = \bar{X} \quad \text{e} \quad \hat{\theta}_2 = \frac{X_1 + X_2}{2}
$$

Verifique se os estimadores são não viciados e consistentes, e compare seus EQMs.

::: {#exr-exr2}
Seja $X_1, \ldots, X_n$ uma amostra aleatória da v.a. $X \sim \text{Bernoulli}(\theta)$. Considere os seguintes estimadores para $\theta$:
:::

$$
\hat{\theta}_1 = 2\bar{X} \quad \text{e} \quad \hat{\theta}_2 = \frac{1}{2}
$$

a.  Verifique se os estimadores são não viciados e consistentes.

b.  Faça um gráfico dos seus EQMs e compare-os.

::: {#exr-exr3}
Seja $X_1, \ldots, X_n$ uma amostra aleatória da v.a. $X \sim \text{Normal}(\mu, 4)$. Considere os seguintes estimadores para $\theta$:
:::

$$
\hat{\theta}_1 = \bar{X} \quad \text{e} \quad \hat{\theta}_2 = 8
$$ a. Verifique se os estimadores são não viciados e consistentes.

b.  Faça um gráfico dos seus EQMs e compare-os.

::: {#exr-exr4}
Seja $X$ uma única observação da $\text{Bernoulli}(\theta)$. Considere os estimadores:
:::

$$
T_1(X) = X \quad \text{e} \quad T_2(X) = \frac{1}{2}
$$ a. $T_1(X)$ e $T_2(X)$ são estimadores não viciados para $\theta$? \\

b.  Calcule o erro quadrático médio de $T_1(X)$ e $T_2(X)$.

::: {#exr-exr5}
Seja $X_1, \ldots, X_n$ uma a.a. da v.a. com f.d.p. $f(x|\theta) = \exp{-(x - \theta)}, \, x > \theta, \, \theta > 0$. Considere:
:::

$$
  \hat{\theta}_1 = \bar{X} \quad \text{e} \quad \hat{\theta}_2 = X_{(1)}
$$

a.  Verifique se os estimadores são não viciados.

b.  Faça um gráfico dos EQMs e compare-os.

<!-- :::{#exr-exr6} -->

<!-- Seja $X_1, \ldots, X_n$ uma a.a. da v.a. $X \sim \text{Uniforme}(0, \theta)$. Considere: -->

<!-- ::: -->

<!-- $$ -->

<!-- \hat{\theta}_1 = c_1 \bar{X} \quad \text{e} \quad \hat{\theta}_2 = c_2 X_{(n)} -->

<!-- $$ -->

<!-- a. Encontre $c_1$ e $c_2$ que tornam os estimadores não viciados. -->

<!-- b. Compare os EQMs. -->

<!-- :::{#exr-exr7} -->

<!-- Seja $X_1, \ldots, X_n$ uma a.a. da v.a. $X$ com média $\theta$ e variância $\sigma^2$. Para quais os valores dos coeficientes $a_i$, $i=1,2, \dots, n$ o estimador $\hat{\theta} = \sum_{i=1}^{n} a_i X_i$ é não-viciado para $\theta$? -->

<!-- ::: -->

::: {#exr-exr8}
Seja $X_1, \ldots, X_n$ uma a.a. da v.a. com f.d.p. $f(x|\theta) = \theta x^{\theta - 1}$, $0 < x < 1$, $\theta > 0$. Mostre que:
:::

$$
\hat{\theta} = \bar{X}
$$ é um estimador não-viciado para $\theta$.

::: {#exr-exr9}
Seja $X_1, \ldots, X_n$ uma a.a. da v.a. $X \sim \text{Normal}(\mu, 1)$. Mostre que $T$ é não viciado para $g(\mu) = \mu^2$.
:::

::: {#exr-exr10}
Seja $X_1, \ldots, X_n$ uma a.a. com f.d.p. $f(x|\theta) = \frac{2x}{\theta^2}$, $0 < x < \theta$, $\theta > 0$. Considere:
:::

$$
\hat{\theta}_1 = c_1 \bar{X} \quad \text{e} \quad \hat{\theta}_2 = c_2 X_{(n)}.
$$

a.  Verifique se são não-viciados.

b.  Compare os EQMs.

::: {#exr-exr11}
Seja $X_1, \ldots, X_n \sim \text{Normal}(0, \sigma^2)$ e $V^2 = \sum_{i=1}^{n} X_i^2$, considere:
:::

$$
\hat{\sigma}^2_c = c V^2
$$ a. Encontre o EQM.

b.  Determine $c$ que minimiza o EQM.

::: {#exr-exr12}
Sejam $X_1, \ldots, X_n$ uma a.a. da v.a. $X$, com função de densidade:
:::

$$
f(x) = \theta x^{\theta - 1} I_{(0,1)}(x), \quad \theta > 0
$$

a.  Mostre que $X$ pertence à Família Exponencial.\
b.  Encontre o limite inferior da variância dos estimadores não viciados de $\theta$.\
c.  Encontre uma estatística suficiente para $\theta$.\
d.  Calcule o valor esperado desta estatística.

::: {#exr-exr13}
Seja $X_1, \ldots, X_n$ uma amostra aleatória da distribuição:
:::

$$
f(x) = \exp \left\{ -(x - \theta) \right\} I_{(\theta, \infty)}(x), \quad \theta > 0
$$

a.  Obtenha uma estatística suficiente para $\theta$.\
b.  Obtenha um estimador não viciado que seja função da estatística suficiente.

::: {#exr-exr14}
Mostre que as seguintes distribuições pertencem à família exponencial:
:::

a.  $\text{Gama}(\alpha, \gamma)$ com $\alpha$ e $\gamma$ desconhecidos.\
b.  $\text{Gama}(\alpha, \gamma)$ com $\alpha$ conhecido e $\gamma$ desconhecido.\
c.  $\text{Beta}(a, b)$ com $a$ e $b$ desconhecidos.\
d.  $\text{Beta}(a, b)$ com $a$ conhecido e $b$ desconhecido.\
e.  $\text{Poisson}(\theta)$.\
f.  Binomial Negativa com número de sucessos $r$ conhecido e $0 < p < 1$ desconhecido.

::: {#exr-exr15}
Para cada item da questão `14`, encontre uma estatística suficiente para os parâmetros de interesse.
:::

::: {#exr-exr16}
Seja $X_1, \ldots, X_n$ uma amostra da distribuição:
:::

$$
f(x_i | \theta) = \frac{1}{2i\theta}, \quad -i(\theta - 1) < x_i < i(\theta + 1), \ \theta > 0
$$

Encontre uma estatística suficiente bidimensional para $\theta$.

::: {#exr-exr17}
Seja $X_1, \ldots, X_n \sim \text{Gama}(2, 1/\theta)$.
:::

a.  Mostre que $X$ pertence à Família Exponencial.\
b.  Obtenha uma estatística suficiente para $\theta$.

::: {#exr-exr18}
Seja $X_1, \ldots, X_n \sim N(0, \sigma^2)$.
:::

a.  Encontre o limite inferior da variância dos estimadores não viciados de $\sigma^2$.\
b.  Obtenha uma estatística suficiente para $\sigma^2$.\
c.  Obtenha um estimador não viciado que seja função da estatística suficiente.\
d.  Verifique se este estimador é eficiente.

::: {#exr-exr19}
Seja $X_1, \ldots, X_n \sim \text{Bin}(2, \theta)$.
:::

a.  Encontre o limite inferior da variância dos estimadores não viciados de $\theta$.\
b.  Obtenha uma estatística suficiente para $\theta$.\
c.  Obtenha um estimador não viciado que seja função da estatística suficiente.\
d.  Verifique se este estimador é eficiente.

<!-- :::{#exr-exr20} -->

<!-- Seja $X_1, \ldots, X_n \sim N(\mu, 1)$. -->

<!-- ::: -->

<!-- a. Mostre que o estimador $\hat{\alpha} = \bar{X}^2 - \frac{1}{n}$ é não viciado para $g(\mu) = \mu^2$.   -->

<!-- b. Encontre o limite inferior da variância dos estimadores não viciados de $g(\mu) = \mu^2$.   -->

<!-- c. Verifique se $\hat{\alpha}$ é eficiente.   -->

<!-- $$ -->

<!-- \text{Var}(\hat{\alpha}) \geq \left[ g'(\theta) \right]^2 \frac{1}{n \, \mathbb{E}\left[\left(\frac{\partial \log f(X|\theta)}{\partial \theta}\right)^2\right]} -->

<!-- $$ -->

::: {#exr-exr20}
Sejam $Y_1, \ldots, Y_n$ independentes com $Y_i \sim N(\beta x_i, \sigma^2)$.
:::

a.  Obtenha uma estatística suficiente para $\beta$ e $\sigma^2$.\
b.  Obtenha o ENVVUM para $\beta$ e $\sigma^2$.

::: {#exr-exr22}
Seja $X_1, \ldots, X_n$ da v.a. com densidade:
:::

$$
f(x | \theta) = \frac{2x}{\theta^2}, \quad 0 < x < \theta, \ \theta > 0
$$

Obtenha uma estatística suficiente para $\theta$.

::: {#exr-exr23}
Seja $X_1, \ldots, X_n \sim \text{Bernoulli}(\theta)$.
:::

a.  Obtenha o ENVVUM para $\theta$.\
b.  Obtenha o ENVVUM para $\theta(1 - \theta).$.

<!-- :::{#exr-exr24}  -->

<!-- Seja $X_1, \ldots, X_n \sim \text{Poisson}(\theta).$.   -->

<!-- ::: -->

<!-- A estatística $T = X_1 + 2X_2$ é suficiente para $\theta$? -->

::: {#exr-exr25}
Seja $X_1, \ldots, X_n$ com densidade:
:::

$$
f(x | \mu, \sigma) = \frac{1}{\sigma} \exp\left\{-\frac{(x - \mu)}{\sigma}\right\}, \quad \mu < x < \infty, \ 0 < \sigma < \infty
$$

Encontre uma estatística bidimensional para o vetor $(\mu, \sigma)$.

<!-- :::{#exr-exr26}  -->

<!-- Em estudos de genética, o modelo Binomial é frequentemente utilizado, exceto quando a observação $x = 0$, pois é impossível de ocorrer. Nestes casos, a amostragem será realizada a partir da seguinte distribuição truncada: -->

<!-- ::: -->

<!-- $$ -->

<!-- P(X = x) = -->

<!-- \begin{cases}  -->

<!-- \binom{m}{x} p^x (1 - p)^{m-x} / \left[ 1 - (1 - p)^m \right], & \text{se } x \in \{1, 2, \dots, m\} \\ -->

<!-- 0, & \text{caso contrário}. -->

<!-- \end{cases} -->

<!-- $$ -->

<!-- Encontre o EMV para $p$ para quando $m = 2$ e o tamanho da amostra é $n$. -->

<!-- :::{#exr-exr27} -->

<!-- Sejam $X_1, \dots, X_n$ uma a.a. da v.a. $X \sim \text{Exp}(\lambda)$.   -->

<!-- Encontre o EMV para $\lambda$. -->

<!-- ::: -->

<!-- :::{#exr-exr28} -->

<!-- Seja $X_1, \dots, X_n$ uma a.a. de $X \sim \text{Unif}(\theta, \theta + 1)$.   -->

<!-- ::: -->

<!-- a.Obtenha um estimador via método de momentos.   -->

<!-- b. Obtenha um estimador via método da máxima verossimilhança. -->

<!-- ::: {#exr-exr29} -->
<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X \sim \text{Gama}(2, 1/\theta)$. -->
<!-- ::: -->

<!-- a.Obtenha o EMV para $\theta$.\ -->
<!-- b. Obtenha a distribuição para grandes amostras do estimador obtido no item a). -->

<!-- ::: {#exr-exr30} -->
<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X$, com função de densidade dada por: -->
<!-- ::: -->

<!-- $$ -->
<!-- f(x \mid \theta) = \frac{x + 1}{\theta (\theta + 1)} \exp\left\{-\frac{x}{\theta}\right\}, \quad x > 0, \theta > 0. -->
<!-- $$ -->

<!-- a.Obtenha o EMV para $\theta$.\ -->
<!-- b. Obtenha a distribuição para grandes amostras do estimador obtido no item a).\ -->
<!-- c. Obtenha um estimador via método de momentos. -->

<!-- ::: {#exr-exr31} -->
<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X \sim \text{Poisson}(\theta)$. Seja $g(\theta) = \exp\{-\theta\}$. -->
<!-- ::: -->

<!-- a.Obtenha o EMV para $g(\theta)$.\ -->
<!-- b. Obtenha a distribuição para grandes amostras do estimador obtido no item a). -->

<!-- :::{#exr-exr32}   -->

<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X \sim N(0, \sigma^2)$.   -->

<!-- ::: -->

<!-- a.Obtenha o EMV para $\sigma^2$.   -->

<!-- b. Obtenha o EMV para $\sigma$. -->

<!-- ::: {#exr-exr33} -->
<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X$, com função de densidade dada por: -->
<!-- ::: -->

<!-- $$ -->
<!-- f(x \mid \theta) = \theta (1 + x)^{-(1+\theta)} I_{(0, \infty)}(x), \quad \theta > 0. -->
<!-- $$ -->

<!-- a.Obtenha o EMV para $1/\theta$.\ -->
<!-- b. Obtenha a distribuição para grandes amostras do estimador obtido no item a).\ -->
<!-- c. Obtenha um estimador via método de momentos. -->

<!-- :::{#exr-exr34}   -->

<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X \sim \text{Poisson}(\theta)$. Seja $g(\theta) = (1 + \theta) \exp\{-\theta\}$.   -->

<!-- Obtenha o EMV para $g(\theta)$. -->

<!-- ::: -->

<!-- :::{#exr-exr35}   -->

<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X$, com função de densidade dada por: -->

<!-- ::: -->

<!-- $$ -->

<!-- f(x \mid \theta) = \theta x^{\theta - 1} I_{(0, 1)}(x), \quad \theta > 0. -->

<!-- $$ -->

<!-- a.Encontre o EMV para $\theta$.   -->

<!-- b. Encontre o EMV para $g(\theta) = \frac{\theta}{1 + \theta}$. -->

<!-- ::: {#exr-exr36} -->
<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X$, com função de densidade dada por: -->
<!-- ::: -->

<!-- $$ -->
<!-- f(x \mid \theta) = \frac{2x}{\theta^2}, \quad 0 < x < \theta, \theta > 0. -->
<!-- $$ -->

<!-- a.Obtenha o EMV para $g(\theta) = \theta + \theta^2$.\ -->
<!-- b. Obtenha um estimador para $\theta$ via métodos de momentos. -->

<!-- ::: {#exr-exr37} -->
<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X$, com função de densidade dada por: -->
<!-- ::: -->

<!-- $$ -->
<!-- f(x \mid \theta) = \frac{\theta}{x^2}, \quad x > \theta, \theta > 0. -->
<!-- $$ -->

<!-- a.Obtenha o EMV para $\theta$.\ -->
<!-- b. Obtenha o EMV para $g(\theta) = E\left(\frac{1}{X}\right)$. -->

<!-- ::: {#exr-exr38} -->
<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória obtida a partir da distribuição: -->
<!-- ::: -->

<!-- $$ -->
<!-- f(x) = \exp\{-(x - \theta)\} I_{(\theta, \infty)}(x), \quad \theta > 0. -->
<!-- $$ -->

<!-- a.Obtenha o EMV para $\theta$.\ -->
<!-- b. Obtenha um estimador para $\theta$ via métodos de momentos. -->

<!-- ::: {#exr-exr39} -->
<!-- Seja $Y_1, \dots, Y_n$ variáveis aleatórias independentes com $Y_i \sim N(\alpha + \beta x_i, \sigma^2)$, em que $x_i$ é conhecido para todo $i = 1, \dots, n$.\ -->
<!-- Encontre o EMV para $\alpha$, $\beta$ e $\sigma^2$. -->
<!-- ::: -->

<!-- ::: {#exr-exr40} -->
<!-- Seja $X_1, \dots, X_n$ uma amostra aleatória da v.a. $X \sim \text{Ber}(\theta)$. -->
<!-- ::: -->

<!-- a.Encontre o EMV para $\text{Var}(X)$.\ -->
<!-- b. Obtenha a distribuição para grandes amostras do estimador obtido no item a). -->
